const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const employeesRouter = require('./employeesRouter')
const productsRouter = require('./productsRouter')
const brandRouter = require('./brandRouter')
const suppliersRouter = require('./suppliersRouter')
const clubCradsRouter = require('./clubCradsRouter')
const accessLevelRouter = require('./accessLevelRouter')
const cardTariffRouter = require('./cardTariffRouter')
const groupWorkoutsController = require('./groupWorkoutsController')
const serviceRouter = require('./serviceRouter')
const positionEmployeesRouter = require('./positionEmployeesRouter')
const trainingRoomRouter = require('./trainingRoomRouter')
const workoutSchedulesRouter = require('./workoutSchedulesRouter')

router.use('/user', userRouter)
router.use('/employees', employeesRouter)
router.use('/products', productsRouter)
router.use('/brand', brandRouter)
router.use('/suppliers', suppliersRouter)
router.use('/clubCrads', clubCradsRouter)
router.use('/access', accessLevelRouter)
router.use('/Tariff', cardTariffRouter)
router.use('/group', groupWorkoutsController)
router.use('/service', serviceRouter)
router.use('/position', positionEmployeesRouter)
router.use('/training', trainingRoomRouter)
router.use('/schedule', workoutSchedulesRouter)

module.exports = router

