export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/user'
export const INTRO_ROUTE = '/intro'
export const STORE_ROUTE = '/store'
export const PRODUCT_ROUTE = '/product'
export const ACCOUNT_ROUTE = '/account'
export const GYM_ROUTE = '/gym'
export const AQUA_ROUTE = '/aqua'
export const GROUPWORKOUT_ROUTE = '/group'
export const SPA_ROUTE = '/spa'
export const SALES_ROUTE = '/sales'
export const SHEDULE_ROUTE = '/shedule'
export const CARD_ROUTE = '/cards'

